name: globin

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 */5 * *" 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v5
        uses: actions/setup-go@v6
        with:
          go-version: '>=1.24.6'
        run: go mod tidy
        run: go test . -v
