name: marselo

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v6
        with:
          go-version: '>=1.24.6'
      - name: Another one
        run: |
          go get -u ./...
          go mod tidy
          go test . -v
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add go.mod go.sum
          git commit -m "[みい〜]: update dependencies"
          git push origin main